### ISSUE TITLE
don't work on 3.2.0

### ISSUE THREAD

**Issue by msneet** [fathomssen/redmine_edit_custom_fields#2] opened 2016-01-28 14:38 UTC
```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
```

**Comment by fathomssen** [comment] 2016-01-29 11:52
Hi @msneet 

Could you please paste the corresponding part of your `production.log` file? On my 3.2.0 installation, the plugin runs flawfless.

Have you performed the migration as mentioned in the README file?

`rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production`

Best regards
Frederick Thomssen

**Comment by msneet** [comment] 2016-01-29 14:22
I'm using Bitnami Redmine VMware Virtual Machine. Environment is shown above. 
I followed plugin installation guide and of course performed the migration. I tryed different ways:
`rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production`
and 
`rake redmine:plugins RAILS_ENV=production`
Rake tast is aborted always! So `production.log` is useless. And i don't know how to get detailed logs from rake task, because i'm new to linux and ROR. Could you help me to find proper log? 

Plugin folder is exactly `redmine_edit_custom_fields`.
`Bundle install` worked fine before migration.

**Comment by msneet** [comment] 2016-01-29 14:25
I followed this way for plugin installation:

```
cd /opt/bitnami/apps/redmine/htdocs 
bundle install --without development test postgresql sqlite --no-deployment
bundle install --without development test postgresql sqlite --deployment
bundle exec rake redmine:plugins RAILS_ENV=production
```

**Comment by fathomssen** [comment] 2016-01-29 19:59
Have you tried to actually use Redmine? First without the plugin, then with the plugin?

Which command do you run to test the installation? What is the error message?

**Comment by msneet** [comment] 2016-03-03 08:41
```
rake tast aborted
SystemStackError: stack level too deep
```

**Comment by fathomssen** [comment] 2016-03-09 16:39
Yes, I got that you have got a problem with the tests. But does your Redmine installation work?

**Comment by gmonthiers** [comment] 2016-03-10 10:10
Hello,
We have a problem too with Redmine 3.2.0.

rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production --trace
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
NameError: uninitialized constant DefaultCustomQuery
/var/www/html/redmine-3.2.0/plugins/redmine_edit_custom_fields/lib/custom_field_patch.rb:37:in `<top (required)>'
/var/www/html/redmine-3.2.0/plugins/redmine_edit_custom_fields/init.rb:39:in`block in <top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in`block in make_lambda'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in`block in simple'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in`block in call'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in`call'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in`_run_prepare_callbacks'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:83:in`prepare!'
/usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:50:in`block in module:Finisher'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in`run'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.1.0/tsort.rb:226:in`block in tsort_each'
/usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:427:in`each_strongly_connected_component_from'
/usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in`each'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in`each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/local/lib/ruby/2.1.0/tsort.rb:205:in`tsort_each'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:352:in`initialize!'
/var/www/html/redmine-3.2.0/config/environment.rb:14:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:328:in`require_environment!'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:248:in`call'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:248:in `block in execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:243:in`each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:243:in `execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:187:in`block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:180:in`invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:207:in`each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:207:in `invoke_prerequisites'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:186:in`block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:180:in`invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/task.rb:173:in `invoke'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:150:in`invoke_task'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:106:in`each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:115:in`run_with_threads'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:78:in`block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/lib/rake/application.rb:75:in`run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.0.1/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in`load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

Do you have an idea for this error ?

**Comment by fathomssen** [comment] 2016-03-10 10:25
Hi @gmonthiers 

Thanks for reporting this bug.

For some reason, there still was a dependency on the DefaultCustomQuery plugin which is unnecessary by now. I have removed it in v0.0.3.

As I got no further information on the problem reported by @msneet, I will now close this issue. Feel free to re-open it if you have got are any further information on this issue.

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment] 2016-03-10 10:31
Btw: If the plugin works for you, please feel free to rate it on the [Redmine plugin page](https://www.redmine.org/plugins/redmine_edit_custom_fields)

**Comment by gmonthiers** [comment] 2016-03-10 10:53
Hi,

Thanks. It’s OK now.

I try to create an account on redmine.org to rate your plugin, but it’s seem they have a problem to send me the activation mail…

I’ll do it when my account on redmine.org will be set.

Gwenaël Monthiers
SG – Systèmes d’Information

 [http://srv_apache.stur.local/icons/kr.jpg]
Partenaire de Rennes Métropole, nous facilitons vos déplacements.
Rue Jean-Marie Huchet
CS 94001
35040 Rennes Cedex
Avant d'imprimer ce document, pensez à l'environnement.

Interne   : 30 41
Externe  : 02 99 77 50 41
Mobile   : 07 78 68 88 13

gwenael.monthiers@keolis.commailto:gwenael.monthiers@keolis.com

De : Frederick Thomssen [mailto:notifications@github.com]
Envoyé : jeudi 10 mars 2016 11:32
À : fathomssen/redmine_edit_custom_fields
Cc : MONTHIERS Gwenael
Objet : Re: [redmine_edit_custom_fields] don't work on 3.2.0 (#2)

Btw: If the plugin works for you, please feel free to rate it on the Redmine plugin pagehttps://www.redmine.org/plugins/redmine_edit_custom_fields

—
Reply to this email directly or view it on GitHubhttps://github.com/fathomssen/redmine_edit_custom_fields/issues/2#issuecomment-194781506.

---

## Ce message et toutes les pièces jointes sont établis à l’intention exclusive de ses destinataires et sont confidentiels. L’intégrité de ce message n’étant pas assurée sur Internet, Keolis ne peut être tenu responsable des altérations qui pourraient se produire sur son contenu. Toute publication, utilisation, reproduction, ou diffusion, même partielle, non autorisée préalablement par Keolis, est strictement interdite. Si vous n’êtes pas le destinataire de ce message, merci d’en avertir immédiatement l’expéditeur et de le détruire.

This message and any attachment are intended solely for the addressees and are confidential. Keolis may not be held responsible for their contents whose accuracy and completeness cannot be guaranteed over the Internet. Unauthorized use, disclosure, distribution, copying, or any part thereof is strictly prohibited. If you are not the intended recipient of this message, please notify the sender immediately and delete it.

**Comment by msneet** [comment] 2016-03-10 11:38
I've tried new version. Result is the same:
rake task aborted

My Redmine installation works. Plugin is shown in Administration->Plugins. 
I have granted permission "edit custom field" to manager and checked module in project settings. When i've pressed button "save" an error occured: redmine 500 error (internal error).
Here is my production log:

```

Started HEAD "/" for 127.0.0.1 at 2016-03-10 11:22:51 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (17.4ms)
Completed 200 OK in 441ms (Views: 328.4ms | ActiveRecord: 7.7ms)
Started GET "/" for 192.168.0.100 at 2016-03-10 11:23:16 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (44.6ms)
Completed 200 OK in 65ms (Views: 56.1ms | ActiveRecord: 1.5ms)
Started GET "/login" for 192.168.0.100 at 2016-03-10 11:23:19 +0000
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (5.9ms)
Completed 200 OK in 25ms (Views: 20.5ms | ActiveRecord: 1.3ms)
Started POST "/login" for 192.168.0.100 at 2016-03-10 11:23:25 +0000
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"cwnlB7v3mlb3o7olR6Gq6H8XU9cesWFraZdmsDbjK0vmpaC9s6Kji2wPxt4fMPygz2o2i2K+IAFqrd45Hd+P0w==", "back_url"=>"http://192.168.0.231/", "username"=>"user", "password"=>"[FILTERED]", "login"=>"Вход »"}
  Current user: anonymous
Successful authentication for 'user' from 192.168.0.100 at 2016-03-10 11:23:25 UTC
Redirected to http://192.168.0.231/
Completed 302 Found in 45ms (ActiveRecord: 12.1ms)
Started GET "/" for 192.168.0.100 at 2016-03-10 11:23:25 +0000
Processing by WelcomeController#index as HTML
  Current user: user (id=1)
  Rendered welcome/index.html.erb within layouts/base (8.0ms)
Completed 200 OK in 38ms (Views: 23.6ms | ActiveRecord: 6.0ms)
Started GET "/admin" for 192.168.0.100 at 2016-03-10 11:23:27 +0000
Processing by AdminController#index as HTML
  Current user: user (id=1)
  Rendered admin/_menu.html.erb (4.4ms)
  Rendered admin/index.html.erb within layouts/admin (8.2ms)
  Rendered layouts/base.html.erb (11.6ms)
Completed 200 OK in 41ms (Views: 28.0ms | ActiveRecord: 4.5ms)
Started GET "/admin/plugins" for 192.168.0.100 at 2016-03-10 11:23:29 +0000
Processing by AdminController#plugins as HTML
  Current user: user (id=1)
  Rendered admin/plugins.html.erb within layouts/admin (2.8ms)
  Rendered admin/_menu.html.erb (3.5ms)
  Rendered layouts/base.html.erb (11.0ms)
Completed 200 OK in 28ms (Views: 19.3ms | ActiveRecord: 4.4ms)
Started GET "/admin/plugins" for 192.168.0.100 at 2016-03-10 11:25:10 +0000
Processing by AdminController#plugins as HTML
  Current user: user (id=1)
  Rendered admin/plugins.html.erb within layouts/admin (1.1ms)
  Rendered admin/_menu.html.erb (3.9ms)
  Rendered layouts/base.html.erb (170.7ms)
Completed 200 OK in 186ms (Views: 176.6ms | ActiveRecord: 4.4ms)
Started GET "/roles" for 192.168.0.100 at 2016-03-10 11:25:23 +0000
Processing by RolesController#index as HTML
  Current user: user (id=1)
  Rendered roles/index.html.erb within layouts/admin (15.4ms)
  Rendered admin/_menu.html.erb (4.8ms)
  Rendered layouts/base.html.erb (10.5ms)
Completed 200 OK in 51ms (Views: 38.8ms | ActiveRecord: 4.9ms)
Started GET "/roles/3/edit" for 192.168.0.100 at 2016-03-10 11:25:25 +0000
Processing by RolesController#edit as HTML
  Parameters: {"id"=>"3"}
  Current user: user (id=1)
  Rendered roles/_form.html.erb (33.0ms)
  Rendered roles/edit.html.erb within layouts/admin (38.6ms)
  Rendered admin/_menu.html.erb (3.6ms)
  Rendered layouts/base.html.erb (11.2ms)
Completed 200 OK in 67ms (Views: 52.8ms | ActiveRecord: 8.1ms)
Started PATCH "/roles/3" for 192.168.0.100 at 2016-03-10 11:25:45 +0000
Processing by RolesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"AcSMjAgDiNhBHNTTrzPgA3uJU3E0q9t5TP4fkS2E+be9efQgM8o0rOtYpD6aZzL/R1Pq7mm/Hz481N5CMC0wjA==", "role"=>{"name"=>"Manager", "assignable"=>"1", "issues_visibility"=>"all", "time_entries_visibility"=>"all", "users_visibility"=>"all", "all_roles_managed"=>"1", "managed_role_ids"=>[""], "permissions"=>["add_project", "edit_project", "close_project", "select_project_modules", "manage_members", "manage_versions", "add_subprojects", "edit_attachments", "delete_attachments", "manage_boards", "add_messages", "edit_messages", "edit_own_messages", "delete_messages", "delete_own_messages", "view_calendar", "add_documents", "edit_documents", "delete_documents", "view_documents", "edit_custom_fields", "manage_files", "view_files", "view_gantt", "manage_categories", "view_issues", "add_issues", "edit_issues", "copy_issues", "manage_issue_relations", "manage_subtasks", "set_issues_private", "set_own_issues_private", "add_issue_notes", "edit_issue_notes", "edit_own_issue_notes", "view_private_notes", "set_notes_private", "delete_issues", "manage_public_queries", "save_queries", "view_issue_watchers", "add_issue_watchers", "delete_issue_watchers", "import_issues", "manage_news", "comment_news", "manage_repository", "browse_repository", "view_changesets", "commit_access", "manage_related_issues", "log_time", "view_time_entries", "edit_time_entries", "edit_own_time_entries", "manage_project_activities", "manage_wiki", "rename_wiki_pages", "delete_wiki_pages", "view_wiki_pages", "export_wiki_pages", "view_wiki_edits", "edit_wiki_pages", "delete_wiki_pages_attachments", "protect_wiki_pages", ""]}, "commit"=>"Save", "id"=>"3"}
  Current user: user (id=1)
Redirected to http://192.168.0.231/roles
Completed 302 Found in 28ms (ActiveRecord: 8.3ms)
Started GET "/roles" for 192.168.0.100 at 2016-03-10 11:25:45 +0000
Processing by RolesController#index as HTML
  Current user: user (id=1)
  Rendered roles/index.html.erb within layouts/admin (11.5ms)
  Rendered admin/_menu.html.erb (3.3ms)
  Rendered layouts/base.html.erb (11.1ms)
Completed 200 OK in 37ms (Views: 26.9ms | ActiveRecord: 4.8ms)
Started GET "/admin/projects" for 192.168.0.100 at 2016-03-10 11:25:47 +0000
Processing by AdminController#projects as HTML
  Current user: user (id=1)
  Rendered admin/projects.html.erb within layouts/admin (8.1ms)
  Rendered admin/_menu.html.erb (4.2ms)
  Rendered layouts/base.html.erb (11.5ms)
Completed 200 OK in 48ms (Views: 26.3ms | ActiveRecord: 4.8ms)
Started GET "/projects/sdfg/settings" for 192.168.0.100 at 2016-03-10 11:25:49 +0000
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"sdfg"}
  Current user: user (id=1)
  Rendered projects/_form.html.erb (41.3ms)
  Rendered projects/_edit.html.erb (46.3ms)
  Rendered projects/settings/_modules.html.erb (6.6ms)
  Rendered projects/settings/_members.html.erb (37.3ms)
  Rendered projects/settings/_versions.html.erb (11.7ms)
  Rendered projects/settings/_issue_categories.html.erb (7.4ms)
  Rendered projects/settings/_wiki.html.erb (3.0ms)
  Rendered projects/settings/_repositories.html.erb (8.7ms)
  Rendered projects/settings/_boards.html.erb (8.8ms)
  Rendered projects/settings/_activities.html.erb (26.7ms)
  Rendered common/_tabs.html.erb (182.2ms)
  Rendered projects/settings.html.erb within layouts/base (185.7ms)
Completed 200 OK in 258ms (Views: 202.5ms | ActiveRecord: 18.1ms)
Started POST "/projects/sdfg/modules" for 192.168.0.100 at 2016-03-10 11:25:52 +0000
Processing by ProjectsController#modules as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"zr6JRcdIxUrvi2by3IcfLgQ49kIzOtknBgREUuE6pvhyA/Hp/IF5PkXPFh/p083SOOJP3W4uHWB2LoWB/JNvww==", "enabled_module_names"=>["issue_tracking", "time_tracking", "news", "documents", "files", "wiki", "repository", "boards", "calendar", "gantt", "edit_custom_fields"], "commit"=>"Save", "id"=>"sdfg"}
  Current user: user (id=1)
Redirected to http://192.168.0.231/projects/sdfg/settings/modules
Completed 302 Found in 25ms (ActiveRecord: 8.0ms)
Started GET "/projects/sdfg/settings/modules" for 192.168.0.100 at 2016-03-10 11:25:52 +0000
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"sdfg", "tab"=>"modules"}
  Current user: user (id=1)
  Rendered projects/_form.html.erb (10.6ms)
  Rendered projects/_edit.html.erb (12.2ms)
  Rendered projects/settings/_modules.html.erb (4.9ms)
  Rendered projects/settings/_members.html.erb (13.9ms)
  Rendered projects/settings/_versions.html.erb (3.4ms)
  Rendered projects/settings/_issue_categories.html.erb (2.0ms)
  Rendered projects/settings/_wiki.html.erb (1.6ms)
  Rendered projects/settings/_repositories.html.erb (1.6ms)
  Rendered projects/settings/_boards.html.erb (1.7ms)
  Rendered projects/settings/_activities.html.erb (9.0ms)
  Rendered plugins/redmine_edit_custom_fields/app/views/edit_custom_fields_settings/_form.html.erb (6.5ms)
  Rendered common/_tabs.html.erb (63.8ms)
  Rendered projects/settings.html.erb within layouts/base (66.6ms)
Completed 500 Internal Server Error in 84ms (ActiveRecord: 12.4ms)

ActionView::Template::Error (Mysql2::Error: Unknown column 'custom_fields.user_editable' in 'where clause': SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND (is_for_all = 1 OR id IN (SELECT DISTINCT cfp.custom_field_id FROM custom_fields_projects cfp WHERE cfp.project_id = 1)) AND `custom_fields`.`user_editable` = 1  ORDER BY `custom_fields`.`position` ASC):
    23: -%>
    24: <div class="box" style="display: none;">
    25:   <h2><%= l 'select_field' %></h2>
    26:   <%= select_tag 'custom_field', getOptions() %><br>
    27:   <em><%=l 'edit_custom_fields.text_allowed' %></em>
    28: </div>
    29: <% getFields().each do |cf| %>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__2689537959462475884_70300092159280'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__2689537959462475884_70300092159280'
  app/helpers/application_helper.rb:324:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__2995369034678801785_70300087706980'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


```

**Comment by fathomssen** [comment] 2016-03-10 11:51
Hi @msneet 

For some reason, the migration seems not to have created the required database field `custom_fields.user_editable`. 

Please revert the plugin database migration using

`rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production VERSION=0`

and then migrate it again using

`rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production`

Please paste the commands' output here if you experience any difficulties.

Best regards
Frederick Thomssen

**Comment by msneet** [comment] 2016-03-10 12:00
`rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production VERSION=0`

rake tast aborted

**Comment by msneet** [comment] 2016-03-10 12:01
I will try to install plugin in a fresh redmine installation. This will take some time.

**Comment by msneet** [comment] 2016-03-10 12:27
on a fresh redmine installation (bitnami 3.2.0-1, ubuntu vmware image) result is the same

**Comment by gmonthiers** [comment] 2016-03-10 12:30
On Redmine 3.2.0 (not bitnami), we don't have this issue.

**Comment by fathomssen** [comment] 2016-03-10 13:48
Hi @msneet 

I tried Bitnami Redmine 3.2.0-2 on Windows 10 x64. After copying the plugin into the plugin directory, I did the following:

`
C:\Bitnami\redmine-3.2.0-2\apps\redmine\htdocs>PATH=C:\Bitnami\redmine-3.2.0-2\ruby\bin

C:\Bitnami\redmine-3.2.0-2\apps\redmine\htdocs>bundle exec rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production
DL is deprecated, please use Fiddle
Migrating redmine_edit_custom_fields (Redmine Edit Custom Fields plugin)...
== 1 AddUserEditableToCustomField: migrating ==================================
-- add_column(:custom_fields, :user_editable, :boolean, {:default=>false, :null=>false})
   -> 0.1862s
== 1 AddUserEditableToCustomField: migrated (0.1982s) =========================
`

Worked like a charm.

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment] 2016-03-10 13:49
Could you possibly grant me access to your Redmine installation? For example, can I access the VMware via SSH to have a look at it myself?

**Closed as completed** 2016-03-18 15:25 UTC
